### ISSUE TITLE
Incorrect game titles after scanning games folder

### ISSUE THREAD

**Issue by CeeNain** [Trixarian/NetherSX2-patch#3] opened 2023-09-01 17:14 UTC
Games don't display the same file name as they do on a file explorer. Re-scanning games doesn't update the names. (Files are on a micro-SD card). The problem started happening with the latest 1.4 Builder version.

![1](https://github.com/Trixarian/NetherSX2-patch/assets/74126204/a437d31e-82dd-4304-973f-706227c02624)
![2](https://github.com/Trixarian/NetherSX2-patch/assets/74126204/20736e2a-4a6e-4228-a443-17827b037b1d)

**Comment by Trixarian** [comment] 2023-09-01 18:15
This was caused by a single entry with spacing issues in GameIndex.yaml (the file that houses the GameDB). Should be fixed shortly and I'll update the download links with the fixed version. Will close this issue once they're uploaded

**Closed** 2023-09-01 18:23 UTC
