### ISSUE TITLE
Metal Gear Solid 3: Subsistence black screen

### ISSUE THREAD

**Issue by ANDRO1D-0502** [Trixarian/NetherSX2-patch#14] opened 2023-09-15 16:45 UTC
Just a black screen on startup MGS 3 Disk 1. Changing settings or running on pure Nether v1.6 doesn't work. On the AetherSX2 and the first versions of Nether, everything worked without problems.

**Comment by Trixarian** [comment] 2023-09-15 19:40
Seems to be caused by the use of InstantDMAHack - apparently it loads at the start of the game when it shouldn't causing race conditions that crashes the emulator. This should be fixed with the next release of NetherSX2-patch

**Comment by hihihihi7657** [comment] 2023-10-03 20:36
When is this going to get fixed I'm still waiting ever since I updated this game has become unplayable and I'm just waiting for you to fix it it's been 3 weeks it should be fixed by now you should have fixed it as soon as you knew about it

**Comment by Trixarian** [comment] 2023-10-03 21:23
I don't have to do a thing. The fix is in the repository and I've given you all the tools to fix it yourself. If you can't wait, do it yourself. Simple as that

**Closed** 2023-12-06 11:38 UTC
Labels: bug
